name: Run Reminder Scheduler

on:
  schedule:
    # Runs every 15 minutes
    # This cron syntax means: "At minute 0, 15, 30, and 45 past every hour, every day"
    - cron: '*/5 * * * *'
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  run_scheduler:
    runs-on: ubuntu-latest # The operating system where the job will run

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Action to check out your repository

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Ensure this matches your Python version (e.g., 3.9, 3.10, 3.11)

      - name: Install Python dependencies
        # We need to install dependencies from requirements.txt located inside the backend folder
        run: pip install -r backend/requirements.txt

      - name: Run the scheduler script
        # Navigate into the backend directory to run scheduler.py
        run: python backend/scheduler.py
        env:
          # Pass your secrets as environment variables to the script
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }} # Make sure this matches your secret name